language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git
  - git clone --depth=1 --branch=master git://github.com/mupen64plus/mupen64plus-core.git deps/mupen64plus-core
env:
 - SSE=none
 - SSE=SSE2
 - SSE=SSSE3
script:
 - make -C projects/unix APIDIR="$(pwd)/deps/mupen64plus-core/src/api/" V=1 clean && LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" OPTFLAGS="-O3" make CC="${CC}" CXX="${CXX}" -j$(nproc) -C projects/unix APIDIR="$(pwd)/deps/mupen64plus-core/src/api/" V=1 all
